# Generated by Django 4.1.1 on 2022-09-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assetmgt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Asset Type")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="assetmodel",
            name="type_of_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assetmgt.assettype",
                verbose_name="Asset Type",
            ),
        ),
    ]
