# Generated by Django 4.1.1 on 2022-10-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assetmgt", "0003_alter_accessories_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessories",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessory",
                to="assetmgt.assetmodel",
                verbose_name="Of Asset",
            ),
        ),
    ]
